#[Info]
site_name: Echo's Notebook
site_url: https://echoesran.github.io/notebook/
repo_name: Echoesran/notebook 
repo_url: https://github.com/Echoesran/notebook
site_description: Echo's Notebook
copyright: Copyright &copy; 2026 <a href="https://github.com/Echoesran" target="_blank" rel="noopener">Echoesran</a>

#[UI]
theme: 
  name: material
